# Generated by Django 4.1.7 on 2023-11-19 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('mandarin', 'Mandarin'), ('spanish', 'Spanish'), ('english', 'English'), ('hindi', 'Hindi'), ('bengali', 'Bengali'), ('portuguese', 'Portuguese'), ('russian', 'Russian'), ('japanese', 'Japanese'), ('punjabi', 'Punjabi'), ('marathi', 'Marathi'), ('telugu', 'Telugu'), ('wu', 'Wu (Shanghainese)'), ('turkish', 'Turkish'), ('korean', 'Korean'), ('french', 'French'), ('german', 'German'), ('vietnamese', 'Vietnamese'), ('tamil', 'Tamil'), ('yue', 'Yue (Cantonese)'), ('urdu', 'Urdu')], max_length=1000)),
                ('language', models.CharField(choices=[('china', 'China'), ('india', 'India'), ('united_states', 'United States'), ('indonesia', 'Indonesia'), ('pakistan', 'Pakistan'), ('brazil', 'Brazil'), ('nigeria', 'Nigeria'), ('bangladesh', 'Bangladesh'), ('russia', 'Russia'), ('mexico', 'Mexico'), ('japan', 'Japan'), ('ethiopia', 'Ethiopia'), ('philippines', 'Philippines'), ('egypt', 'Egypt'), ('vietnam', 'Vietnam'), ('congo', 'Congo (DRC)'), ('turkey', 'Turkey'), ('iran', 'Iran'), ('germany', 'Germany'), ('thailand', 'Thailand')], max_length=1000)),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
